# Generated by Django 5.2.6 on 2025-10-13 18:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Trilha',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('descricao', models.TextField()),
                ('visibilidade', models.BooleanField(default=True)),
                ('dificuldade', models.CharField(choices=[('iniciante', 'Iniciante'), ('intermediario', 'Intermediário'), ('avancado', 'Avançado')], default='iniciante', max_length=20)),
                ('total_salvos', models.PositiveIntegerField(default=0, help_text='Número de usuários que salvaram a trilha')),
                ('categoria', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='trilhas.categoria')),
            ],
        ),
        migrations.CreateModel(
            name='Projeto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('descricao', models.TextField(blank=True)),
                ('ordem', models.PositiveIntegerField(help_text='Ordem do projeto dentro da trilha')),
                ('trilha', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='projetos', to='trilhas.trilha')),
            ],
        ),
        migrations.CreateModel(
            name='Etapa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('texto', models.CharField(max_length=200)),
                ('ordem', models.PositiveIntegerField(help_text='Ordem do projeto dentro da trilha')),
                ('trilha', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='trilhas.trilha')),
            ],
        ),
        migrations.CreateModel(
            name='ProgressoEtapa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('concluida', models.BooleanField(default=False)),
                ('etapa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='trilhas.etapa')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'etapa')},
            },
        ),
    ]
