# Generated by Django 5.2.6 on 2025-10-20 21:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('trilhas', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='progressotrilha',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='trilha',
            name='categoria',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='trilhas.categoria'),
        ),
        migrations.AddField(
            model_name='projeto',
            name='trilha',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='projetos', to='trilhas.trilha'),
        ),
        migrations.AddField(
            model_name='progressotrilha',
            name='trilha',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='progresso_usuarios', to='trilhas.trilha'),
        ),
        migrations.AddField(
            model_name='etapa',
            name='trilha',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='trilhas.trilha'),
        ),
        migrations.AlterUniqueTogether(
            name='progressotrilha',
            unique_together={('user', 'trilha')},
        ),
    ]
