# Generated by Django 5.2.6 on 2025-10-13 21:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trilhas', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ProgressoTrilha',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('em_progresso', 'Em Progresso'), ('pausada', 'Pausada'), ('concluida', 'Concluída')], default='em_progresso', max_length=20)),
                ('progresso_percentual', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('data_inicio', models.DateTimeField(auto_now_add=True)),
                ('ultima_atualizacao', models.DateTimeField(auto_now=True)),
                ('trilha', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='progresso_usuarios', to='trilhas.trilha')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'trilha')},
            },
        ),
        migrations.DeleteModel(
            name='ProgressoEtapa',
        ),
    ]
