# Generated by Django 5.2.6 on 2025-10-20 22:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trilhas', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='trilha',
            name='duracao',
            field=models.CharField(blank=True, help_text="Duração estimada da trilha (ex: '3h', '2 semanas', etc.)", max_length=50, null=True),
        ),
    ]
